//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace HolisticWare {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class plist {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
        [System.Xml.Serialization.XmlElementAttribute("data", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
        [System.Xml.Serialization.XmlElementAttribute("false", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("real", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("true", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class array {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
        [System.Xml.Serialization.XmlElementAttribute("data", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
        [System.Xml.Serialization.XmlElementAttribute("false", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("real", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("true", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
    public partial class dict {
        
        private string[] keyField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("key")]
        public string[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("array", typeof(array))]
        [System.Xml.Serialization.XmlElementAttribute("data", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict))]
        [System.Xml.Serialization.XmlElementAttribute("false", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("integer", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("real", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("true", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/namespace/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        array,
        
        /// <remarks/>
        data,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        dict,
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        real,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/namespace/", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        array,
        
        /// <remarks/>
        data,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        dict,
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        real,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        @true,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/namespace/", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        array,
        
        /// <remarks/>
        data,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        dict,
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        real,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        @true,
    }
}
